# Generated by Django 2.2.3 on 2019-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=8, max_digits=15)),
                ('max', models.DecimalField(decimal_places=8, max_digits=15)),
                ('greenred', models.IntegerField()),
                ('timer', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=15)),
                ('close', models.DecimalField(decimal_places=8, max_digits=15)),
                ('pair', models.CharField(max_length=10)),
                ('ma14', models.DecimalField(decimal_places=8, max_digits=15)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
