# Generated by Django 2.2.3 on 2019-08-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0002_valuesma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesma',
            name='money',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='valuesma',
            name='timer',
            field=models.DateTimeField(db_index=True),
        ),
    ]
