# Generated by Django 2.2.3 on 2019-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0006_hourlyprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyprofit',
            name='asset',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
