# Generated by Django 2.2.3 on 2019-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0008_valueslencomplete_valuesmacomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueslencomplete',
            name='ignore',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='valueslencomplete',
            name='pair',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
