# Generated by Django 2.2.3 on 2019-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0009_auto_20190917_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesMA25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=8, max_digits=15)),
                ('max', models.DecimalField(decimal_places=8, max_digits=15)),
                ('greenred', models.IntegerField()),
                ('timer', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=15)),
                ('close', models.DecimalField(decimal_places=8, max_digits=15)),
                ('pair', models.CharField(max_length=10)),
                ('ma14', models.DecimalField(decimal_places=8, max_digits=15)),
                ('money', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesMA7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=8, max_digits=15)),
                ('max', models.DecimalField(decimal_places=8, max_digits=15)),
                ('greenred', models.IntegerField()),
                ('timer', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=15)),
                ('close', models.DecimalField(decimal_places=8, max_digits=15)),
                ('pair', models.CharField(max_length=10)),
                ('ma14', models.DecimalField(decimal_places=8, max_digits=15)),
                ('money', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesPsyLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=8, max_digits=15)),
                ('max', models.DecimalField(decimal_places=8, max_digits=15)),
                ('greenred', models.IntegerField()),
                ('timer', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=15)),
                ('close', models.DecimalField(decimal_places=8, max_digits=15)),
                ('pair', models.CharField(max_length=10)),
                ('ma14', models.DecimalField(decimal_places=8, max_digits=15)),
                ('money', models.IntegerField(db_index=True)),
            ],
        ),
    ]
