# Generated by Django 2.2.3 on 2019-11-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0012_valuesmaall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuesmaall',
            name='ignore',
        ),
    ]
