# Generated by Django 2.2.3 on 2019-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boanapp', '0013_remove_valuesmaall_ignore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuesmaall',
            old_name='money',
            new_name='money14',
        ),
        migrations.AddField(
            model_name='valuesmaall',
            name='money25',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuesmaall',
            name='money7',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
